---
- name: Macbook basic apps
  hosts: localhost
  connection: local
  vars:
    brew_apps:
      - firefox
      - obsidian
      - slack
      - mattermost
      - zoom
      # - microsoft-teams
      - 1password
      # - 1password-cli
      - vlc
      - openvpn-connect
      - netbirdio/tap/netbird-ui

  tasks:
  - name: Install cask apps
    homebrew_cask:
      name: '{{ item }}'
      state: present
    loop: '{{ brew_apps }}'
