---
- name: Macbook development setup
  hosts: localhost
  connection: local
  vars:
    brew_tools:
      - git
      - vim
      - universal-ctags
      - fzf
      - rg
      - bat
      - eza
      - fd
      - ranger
      - zoxide
      - diskus
      - tree
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - zsh-history-substring-search
      - rustup
      - go
      - pyenv
      - pyenv-virtualenv
      - uv
    casks:
      - iterm2
      - kitty
      - ghostty

  tasks:
    - name: Install basic cli tools
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ brew_tools }}"

    - name: Install cask tools
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: "{{ casks }}"
