---
- name: Install DevOps toolkit
  hosts: localhost
  connection: local
  vars:
    brew_tools:
      - lima
      - kubectl
      - helm
      - k9s
      - kubectx
      - eksctl
      - awscli
      - tfenv
      - jq
      - go

  tasks:
  - name: Install devops tools
    homebrew:
      name: '{{ item }}'
      state: present
    loop: '{{ brew_tools }}'

  - name: Add aws brew tap
    homebrew_tap:
      name: aws/tap
  - name: Install eks-node-viewer
    homebrew:
      name: eks-node-viewer
