---
- name: Install DevOps toolkit
  hosts: localhost
  connection: local
  vars:
    brew_tools:
      - lima
      - kubectl
      - helm
      - k9s
      - kubectx
      - eksctl
      - awscli
      - tfenv

  tasks:
  - name: Install devops tools
    homebrew:
      name: '{{ item }}'
      state: present
    loop: '{{ brew_tools }}'
