---
- name: Personalise setup
  hosts: localhost
  connection: local
  vars:
    src_dir_name: pai
    src_dir_path: '{{ ansible_env.HOME }}/src/{{ src_dir_name }}'

  tasks:
    - name: Set key repeat - highest rate, lowest delay
      osx_defaults:
        domain: NSGlobalDomain
        key: '{{ item.key }}'
        type: float
        value: '{{ item.value }}'
        state: present
      loop:
        - { key: KeyRepeat, value: 2 }
        - { key: InitialKeyRepeat, value: 15 }

    - name: Autohide dock
      osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: true
        state: present

    - name: Create a base dir for all source code
      file:
        path: '{{ src_dir_path }}'
        state: directory

    - name: Clone the dotfiles repo
      git:
        repo: git@github.com:gautamkpai/dotfiles.git
        dest: '{{ src_dir_path }}/dotfiles'

    - name: check if ~/.vim exists & is a symlink
      stat:
        path: '{{ ansible_env.HOME }}/.vim'
      register: sym

    - name: Ensure ~/.vim is not dir
      file:
        path: '{{ ansible_env.HOME }}/.vim'
        state: absent
      when: sym.stat.islnk is defined and sym.stat.islnk == False

    - name: symlink vim configs
      file:
        src: '{{ src_dir_path }}/dotfiles/{{ item }}'
        dest: '~/.{{ item }}'
        state: link
      loop:
        - vimrc
        - vim

    - name: symlink git templates dir & globalignore file
      file:
        src: '{{ src_dir_path }}/dotfiles/{{ item }}'
        dest: '~/.{{ item }}'
        state: link
      loop:
        - git_template
        - gitignore_global

    - name: Set git global configs - template dir
      git_config:
        name: '{{ item.name }}'
        scope: global
        value: '{{ item.value }}'
      loop:
        - { name: user.name, value: 'K Gautam Pai' }
        - { name: user.email, value: 'gautampai@gautampai.com' }
        - { name: init.templatedir, value: ~/.git_template }
        - { name: alias.ctags, value: '!.git/hooks/ctags' }
        - { name: core.excludesfile, value: ~/.gitignore_global }
