#!/usr/bin/env ruby

unless system("/usr/local/bin/brew -v")
  puts "Installing homebrew..."
  system %{/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"}
end

unless system("/usr/local/bin/ansible --version")
  puts "Installing ansible..."
  system "/opt/homebrew/bin/brew install ansible"
end

unless Dir.exists?("/tmp/ainulindale/")
  puts "Downloading ainulindale..."
  system "git clone https://github.com/gautamkpai/ainulindale.git /tmp/ainulindale"
end

system "cd /tmp/ainulindale && /opt/homebrew/bin/ansible-playbook 0-test.yml"
