#!/usr/bin/env ruby

unless system("/usr/local/bin/brew -v")
  puts "Installing homebrew..."
  system %{ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"}
end

unless system("/usr/local/bin/ansible --version")
  puts "Installing ansible..."
  system "brew install ansible"
end

unless Dir.exists?("/tmp/ainulindale/")
  puts "Downloading ainulindale..."
  system "git clone https://github.com/gautamkpai/ainulindale.git /tmp/ainulindale"
end

system "cd /tmp/ainulindale && ansible-playbook osx.yml"
