---
- name: Macbook development setup
  hosts: localhost
  connection: local
  vars:
    brew_tools:
      - git
      - vim
      - fzf
      - rg
      - bat

  tasks:
    - name: Install basic cli tools
      homebrew:
        name="{{ item }}"
        state=present
      loop: "{{ brew_tools }}"

    - name: Install iTerm2
      homebrew_cask: name=iterm2 state=present

