---
- name: Macbook development setup
  hosts: localhost
  connection: local

  tasks:
  - name: Update homebrew
    homebrew: update_homebrew=yes

  - name: Install cask
    homebrew: name=caskroom/cask/brew-cask state=present

  - name: Install vim
    homebrew: name=vim state=present

  - name: Install git
    homebrew: name=git state=present

  - name: Install firefox
    homebrew_cask: name=firefox state=present
