---
- name: Macbook development setup
  hosts: localhost
  connection: local

  tasks:
  - include: tasks/base.yml

  - name: Install vim
    homebrew: name=vim state=present

  - name: Install git
    homebrew: name=git state=present

  - name: Install firefox
    homebrew_cask: name=firefox state=present
